### ISSUE TITLE
Server terminated abruptly (error code: 14, error message: 'Socket closed'

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/bazel-orfs#869]
While buildind with bazelisk-linux-amd64 run @bazel-orfs//test:L1MetadataArray_cts, I ofter get the error:

`Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/titan/.cache/bazel/_bazel_titan/f3927351c75ca15471dd28a53a04470c/server/jvm.out')`

I never had this kind of error when building OR.

Log:
```
titan@titan-host:~/bazel-orfs$ ../bazelisk-linux-amd64 run @bazel-orfs//test:L1MetadataArray_cts
Starting local Bazel server (8.6.0) and connecting to it...
INFO: Analyzed target //test:L1MetadataArray_cts (963 packages loaded, 94314 targets configured).
[13,700 / 15,735] 16 actions running
    @@sv-lang+//:libsvlang; 452s linux-sandbox
    Compiling src/drt/src/pa/FlexPA_graphics.cpp [for tool]; 451s linux-sandbox
    Compiling external/or-tools+/ortools/sat/cp_model.pb.cc [for tool]; 451s linux-sandbox
    Compiling src/drt/src/db/obj/frAccess.cpp [for tool]; 451s linux-sandbox
    Compiling src/drt/src/db/drObj/drVia.cpp [for tool]; 451s linux-sandbox
    Compiling src/drt/src/db/infra/KDTree.cpp [for tool]; 451s linux-sandbox
    Compiling src/drt/src/db/drObj/drAccessPattern.cpp [for tool]; 451s linux-sandbox
    Compiling src/drt/src/db/drObj/drNet.cpp [for tool]; 451s linux-sandbox ...

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/titan/.cache/bazel/_bazel_titan/f3927351c75ca15471dd28a53a04470c/server/jvm.out')
```

**Comment by oharboe** [comment]
Need more information, not actionable as is.

**Comment by titan73** [comment]
git b6a42f02ee4816f3d3c9078bf1a2c99ba4de41be
unbuntu 22.04
What other info do you need?

**Comment by titan73** [comment]
I'll test on RHEL8.1

**Comment by oharboe** [comment]
RHEL8.1 EOL 2021

**Comment by oharboe** [comment]
presumably /home/titan/.cache/bazel/_bazel_titan/f3927351c75ca15471dd28a53a04470c/server/jvm.out contained some more information if you still have it...

**Comment by oharboe** [comment]
This is surprising, but harmless, you can drop the the `@bazel-orfs`:

    bazelisk-linux-amd64 run @bazel-orfs//test:L1MetadataArray_cts

Simply:

    bazelisk-linux-amd64 run //test:L1MetadataArray_cts

**Comment by oharboe** [comment]
Try `bazelisk --jobs=1 ...`, just in case it is running out of memory or something? 

disk full?

**Comment by titan73** [comment]
`@bazel-orf` comes from the command `bazel run @bazel-orfs//test:L1MetadataArray_cts` in the doc at https://github.com/The-OpenROAD-Project/bazel-orfs. `@bazel-orf` is used several times there. Maybe the doc should be updated then.

**Comment by titan73** [comment]
For RHEL 8.1, I found `Maintenance Support: Active until May 31, 2029`.

**Comment by titan73** [comment]
On RHEL 8.1 I got:
```
ERROR: /prj/gpca_dig/users/costa/.bazel/output/base/external/bazel_tools/tools/build_defs/repo/utils.bzl:277:21: An error occurred during the fetch of repository 'openroad+':
   Traceback (most recent call last):
        File "/prj/gpca_dig/users/costa/.bazel/output/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 169, column 32, in _http_archive_impl                                                                                       
                remote_patches_info = patch(ctx)
        File "/prj/gpca_dig/users/costa/.bazel/output/base/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 277, column 21, in patch                                                                                                   
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command curl -sSfL --retry 5 --retry-all-errors --retry-delay 5 -o .openroad-submodule-src-sta-509913b1398b36eda23caa1f1f380167465dceee.tar.gz https://github.com/The-Op                                      5dceee.tar.gz && echo '680920e76cdb2f9add4de04db4b24500ef7faa0405c9802f815e7286c106a2ec  .openroad-submodule-src-sta-509913b1398b36eda23caa1f1f380167465dceee.tar.gz' | sha256sum -c - && tar xzf .openroad-                                       --strip-components=1 -C src/sta && rm .openroad-submodule-src-sta-509913b1398b36eda23caa1f1f380167465dceee.tar.gz:                                                                                                                               
curl: option --retry-all-errors: is unknown                                                                                                                                                                                                       
curl: try 'curl --help' or 'curl --manual' for more information      
```                                                                                                                                                                             
I have curl 7.61.1 but `--retry-all-errors` was added in version 7.71.0. Shouldn't this dependencies added to bazel build?

**Comment by titan73** [comment]
Still on RHEL 8.1. After worked around curl issue I get:
```
ERROR: /prj/gpca_dig/users/costa/.bazel/output/base/external/libxcb+/BUILD.bazel:50:9: Executing genrule @@libxcb+//:c_client_bigreq [for tool] failed: (Exit 1): bash failed: error executing Genrule command (from target @@libxcb+//:c_client_bigreq) /bin/bash -c ... (remaining 1 argument skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/libxcb+/c_client", line 639, in <module>
    main()
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/libxcb+/c_client", line 544, in main
    print_verbose("bootstrap sys._base_executable:", sys._base_executable)
AttributeError: module 'sys' has no attribute '_base_executable'
Target //test:L1MetadataArray_cts failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
Looks like a python issue.

**Comment by oharboe** [comment]
Did you try `bazelisk build //:openroad` on OpenROAD standalone?

Perhaps RHEL 8.1 is too old for openroad...

There's no point in fixing snags in bazel-orfs if OpenROAD does not support RHEL 8.1 bazel builds. Also, I'm skeptical of other dependencies w.r.t. building on RHEL 8.1. It may be a deep, deep rabbithole for an older distribution.

**Comment by titan73** [comment]
`bazelisk build //:openroad` works fine on RHEL 8.1 (apart from pandoc and python deps during man page generation).

**Comment by oharboe** [comment]
and openroad-qt?

**Comment by titan73** [comment]
I sorry, I used `bazelisk run --//:platform=gui //:install` as shown in the doc. It has both the qt and web guis.
Is it the same as `//:openroad-qt`?

**Comment by oharboe** [comment]
> I sorry, I used `bazelisk run --//:platform=gui //:install` as shown in the doc. It has both the qt and web guis. Is it the same as `//:openroad-qt`?

Not the same, but I think very similar, haven't used it in a while.

Certainly a good sign!

There's a bunch of PRs that are being merged now. Hopefully things will work better aftewards, but I need the jvm.out error file you have in your initial report to know what's going on with jvm.

**Comment by titan73** [comment]
Thanks for the PRs.
Just tested. No issue with `bazelisk build //:openroad` and `bazelisk build //:openroad-qt`
I'll send jvm.out when I get back home.

**Comment by titan73** [comment]
@oharboe jvm.out contains:
`OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.`
I wonder how a warning could generate an error.
Anyway it seems the issue is gone. I didn't do anything but I can't reproduce it.

**Comment by oharboe** [comment]
> [@oharboe](https://github.com/oharboe) jvm.out contains: `OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.` I wonder how a warning could generate an error. Anyway it seems the issue is gone. I didn't do anything but I can't reproduce it.

I don't think this was it, this is just a warning as you say.

No matter, if it happens again, file a new issue with actionable detail and let's see what we can do.

**Comment by oharboe** [comment]
Thanks for reporting!

**Comment by titan73** [comment]
@oharboe This works now. Thanks for the fixed.
```
2026/09/04 14:04:31 Downloading https://releases.bazel.build/9.1.1/release/bazel-9.1.1-linux-x86_64...
2026/09/04 14:04:31 Skipping basic authentication for releases.bazel.build because no credentials found in /home/costa/.netrc
Downloading: 62 MB out of 62 MB (100%) 
2026/09/04 14:04:40 Signed by Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>
WARNING: Output base '/prj/gpca_dig/users/costa/.bazel/output/base' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server (9.1.1) and connecting to it...
INFO: Invocation ID: c474f993-0331-441c-8904-1ec59da468e7
INFO: Analyzed target //test:L1MetadataArray_cts (972 packages loaded, 97972 targets configured, 143 aspect applications).
INFO: From Generating MOC code from external/qt-bazel+/qt_source/qtbase-6.9.1/src/corelib/kernel/qcfsocketnotifier_p.h [for tool]:
external/qt-bazel+/qt_source/qtbase-6.9.1/src/corelib/kernel/qcfsocketnotifier_p.h: note: No relevant classes found. No output generated.
INFO: Found 1 target...
Target //test:L1MetadataArray_cts up-to-date:
  bazel-bin/test/results/asap7/L1MetadataArray/base/1_1_yosys_canonicalize.rtlil
  bazel-bin/test/results/asap7/L1MetadataArray/base/4_cts.odb
  bazel-bin/test/results/asap7/L1MetadataArray/base/4_cts.sdc
  bazel-bin/test/reports/asap7/L1MetadataArray/base/4_cts_final.rpt
INFO: Elapsed time: 855.268s, Critical Path: 52.48s
INFO: 1669 processes: 14130 action cache hit, 1570 disk cache hit, 24 internal, 75 linux-sandbox.
INFO: Build completed successfully, 1669 total actions
INFO: Running command line: bazel-bin/test/L1MetadataArray_cts.sh
```

**Comment by titan73** [comment]
I can get the the odb of after the cts.
I can I run the whole flow and get a routed odb?
Using `route` instead of `cts` does not work:
```
WARNING: Output base '/prj/gpca_dig/users/costa/.bazel/output/base' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Invocation ID: d75c0e1f-a895-4ccc-ba08-44e470937c4e
INFO: Checking for file changes...
WARNING: Target pattern parsing failed.
ERROR: Skipping '//test:L1MetadataArray_route': no such target '//test:L1MetadataArray_route': target 'L1MetadataArray_route' not declared in package 'test' defined by /prj/gpca_dig/users/costa/bazel-orfs/test/BUILD (did you mean L1MetadataArray_1_cts, L1MetadataArray_cts, L1MetadataArray_place, or L1MetadataArray_synth?)
ERROR: no such target '//test:L1MetadataArray_route': target 'L1MetadataArray_route' not declared in package 'test' defined by /prj/gpca_dig/users/costa/bazel-orfs/test/BUILD (did you mean L1MetadataArray_1_cts, L1MetadataArray_cts, L1MetadataArray_place, or L1MetadataArray_synth?)
INFO: Elapsed time: 1.236s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by oharboe** [comment]
bazel-orfs tries not to run the whole flow to speed up CI.

To find a route target, run:

    bazelisk query ... | grep _route

**Comment by titan73** [comment]
ok thanks. So all designs that have the routing task are small right?
I would had liked a big enough routed design odb file to test the rendering speed of the openroad web gui.

**Comment by oharboe** [comment]
Hold my 🍺

**Comment by oharboe** [comment]
You can build and view any ORFS design from bazel-orfs, see https://github.com/The-OpenROAD-Project/bazel-orfs#quick-start

**Comment by titan73** [comment]
ok thank.
